rabbitmqadmin --quiet purge queue name="Food"
echo "Purged Food"
rabbitmqadmin --quiet purge queue name="Meetings"
echo "Purged Meetings"
rabbitmqadmin --quiet purge queue name="Rooms"
echo "Purged Rooms"
rabbitmqadmin --quiet purge queue name="Wishes"
echo "Purged Wishes"
rabbitmqadmin --quiet purge queue name="Noise"
echo "Purged Noise"
rabbitmqadmin --quiet purge queue name="Seating"
echo "Purged Seating"
rabbitmqadmin --quiet purge queue name="Classrooms"
echo "Purged Classrooms"
rabbitmqadmin --quiet purge queue name="Auditorium"
echo "Purged Auditorium"
