#!/usr/bin/env python
import pymongo
import time
import pika

# method to receive statements generated by RabbitMQ
def callback(ch, method, properties, body):
    print("%r:%r" % (method.routing_key, body))
    ch.stop_consuming()

# start instance of Mongo Client and RabbitMQ Channel
db = pymongo.MongoClient().test
connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
channel = connection.channel()
# declare queues (does nothing if queues already exist)


# event loop for sending commands
while 1:
    # First recieve input from keyboard
    message = input("Type message command:")
    print("[Checkpoint 01", time.time(), "] Message Captured:", message)
    # construct msg ID for each message received
    MsgID = "team_19$" + str(time.time())

    # Parsing message to MongoDB format
    if message[0:2:] == 'p:':
        #produce
        action = 'p'
        place = message[message.find(':')+1:message.find('+'):]
        queue = message[message.find('+')+1:message.find('"')-1:]
        cmdMess = message[message.find('"')+1:message.rfind('""'):]
        #construct command in db format
        command = {
                    "Action": action,
                    "Place": place,
                    "MsgID": MsgID,
                    "Subject": queue,
                    "Message": cmdMess
                  }

        # Insert command into mongoDB
        print("[Checkpoint 02 ", time.time(), "] Store command in MongoDB instance:", command)
        db.commands.insert_one(command)

        # send command to rabbit MQ and receive result/response
        channel.exchange_declare(exchange=place, exchange_type='direct')
        channel.basic_publish(exchange=place, routing_key=queue, body=cmdMess)


    elif message[0:2:] == 'c:':
        #consume
        action = 'c'
        place = message[message.find(':')+1:message.find('+'):]
        queue_name = message[message.find('+')+1::]
        command = {
                    "Action": action,
                    "Place": place,
                    "MsgID": MsgID,
                    "Subject": queue_name,
                  }

        # insert command into mongoDB
        print("[Checkpoint 02 ", time.time(), "] Store command in MongoDB instance:", command)
        db.commands.insert_one(command)

        # send command to rabbit MQ and receive result/response
        channel.queue_bind(exchange=place, queue=queue_name, routing_key=queue)
        channel.basic_consume(callback, queue=queue_name, no_Ack=True)
        try:
            channel.start_consuming()
        except KeyBoardInterrupt:
            channel.stop_consuming()

    else:
        print("No command recieved")
        continue


connection.close()
